name: texgen
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Repo
        uses: actions/checkout@v3
      - name: Tex Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "src.tex"
      - name: Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload 
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./file1.pdf
          asset_name: file1.pdf
          asset_content_type: pdf
