name: texgen
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Repo
        uses: actions/checkout@v3
      - name: Tex Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "src.tex"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
