name: texgen

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src.tex

      - name: hi
        run: |
          ls
          git status
          rm Resume.pdf
          mv src.pdf Resume.pdf
          ls
          git add Resume.pdf
        

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: src.pdf
